SwaprHQ/swapr-sdk

README.md
package.json
src/constants.ts
src/entities/pair.ts
test/constants.test.ts
test/pair.test.ts
yarn.lock

- Replace uniswap for dxswap in package and readme.
- Integrate dxswap-core dependency.
- Update factory address and init code hash.

Change uniswap for dxswap

---

package.json
src/abis/staking-rewards-distribution-factory.json
src/constants.ts
src/entities/pair.ts

Includes the staking reward contracts Rinkeby instance address and ABI, along with a minor `Pair` equality check needed for the liquidity mining UI to work.

Liquidity mining related work

---

src/entities/DistributionCampaignBase.ts
src/entities/fractions/price.ts
src/entities/liquidity-mining-campaign.ts
src/entities/single-sided-liquidity-mining-campaign.ts
src/entities/trades/0x-trade.ts
src/entities/trades/interfaces/trade.ts
src/entities/trades/routable-platform/uniswap-v2-routable-platform.ts
src/entities/trades/uniswap-v2-trade.ts

Refactors the function's arguments to use object params (and destructing).

chore: use object params for function arguments 

---

src/entities/trades/curve-trade/CurveTrade.ts

Addreses https://github.com/levelkdev/dxswap-dapp/pull/616#issuecomment-1059092651

fix: Curve trade exact out

---

.eslintrc.js
.github/workflows/CI.yml
.prettierignore
.prettierrc
package.json
yarn.lock

- Adds PR CI: lint, build and test to PRs against `develop` and `main`

chore: add GitHub actions

---

package.json
src/entities/trades/curve/CurveTrade.ts
src/entities/trades/curve/pools/pools.ts
test/curve-trade.test.ts
yarn.lock

- Fixes a bug where if pool quote return `BigNumber.from(0)` and results in `outputAmount = 0`. Hence, it [breaks the UI](https://github.com/levelkdev/swapr-dapp/pull/616#issuecomment-1074361444)
- Removes unused packages.

fix: Curve division by zero

---

package.json
src/entities/trades/curve/CurveTrade.ts
src/entities/trades/curve/abi/abi.ts
src/entities/trades/curve/contracts/contracts.ts
src/entities/trades/curve/types.ts
src/entities/trades/utils.ts
test/curve-trade.test.ts
yarn.lock

Gnosis Chain's native asset is the xDAI stablecoin. This PR adds support for trading between xDAI and USDC and xDAI and USDT by using a un/wrapper contract that handles deposits and withdrawals.

feature: add support for native xDAI in Curve

---

.github/workflows/CI.yml
graphql-codegen.yml
package-lock.json
package.json
src/entities/trades/routable-platform/uniswap-v2-routable-platform.ts
src/entities/trades/uniswap-v2/UniswapV2.ts
src/entities/trades/uniswap-v2/pairs/fees.ts
src/entities/trades/uniswap-v2/pairs/index.ts
src/entities/trades/uniswap-v2/pairs/pairs.ts
src/entities/trades/uniswap-v2/pairs/queries.ts
src/entities/trades/uniswap-v2/pairs/types.ts

Adds additional methods to find the common pairs between tokens A and B from the subgraph.

feature: compute Uniswap v2 common pairs from The Graph

---

src/entities/trades/uniswap/Uniswap/Uniswap.spec.ts
src/entities/trades/uniswap/Uniswap/Uniswap.ts
src/entities/trades/uniswap/utils/index.ts
src/entities/trades/uniswap/utils/nativeCurrency.ts
tsconfig.json

Adds NativeCurreny implementation for MATIC

bugfix: Uniswap Matic support on Polygon

---

src/entities/pair.ts
src/entities/trades/uniswap-v2/UniswapV2.spec.ts

- Added a fix for #100 with some integration tests to validate them.

bugfix: Pair class bug with default parameters

---

src/entities/trades/gnosis-protocol/GnosisProtocolTrade.ts

Fix currency used when creating out trades.

Fix GnosisProtocol currency

---

src/entities/trades/gnosis-protocol/constants.ts

Replaces the placeholder with the actual payload: hex digest

feature: add COW app data

---

.prettierrc
src/entities/platforms-breakdown.ts
src/entities/trades/0x/0xTrade.ts
src/entities/trades/0x/constants.ts
src/entities/trades/0x/index.ts
src/entities/trades/0x/types.ts
src/entities/trades/0x/utils.ts
src/entities/trades/index.ts
src/entities/trades/routable-platform/RoutablePlatform.ts
test/0x-trade.test.ts

#[1053](https://github.com/levelkdev/swapr-dapp/issues/1053)
* fix slippagePercentage
* add price impact
* add Polygon chain to zeroX
* clean the code

update zeroX trade for slippage and price impact

---

bin/cow-app-data.ts
package-lock.json
package.json
src/entities/trades/gnosis-protocol/GnosisProtocolTrade.ts
src/entities/trades/gnosis-protocol/app-data.json
src/entities/trades/gnosis-protocol/constants.ts

Adds a new a script `codegen:cow` to generate app data from the Cow SDK. App data are uploaded to IPFS using Pinata

feature: update CoW appData to latest schema

---

src/entities/trades/curve/abi/abi.ts
src/entities/trades/curve/abi/common.ts
src/entities/trades/curve/pools/pools.ts

Fixes wETH/wBTC trade on arbitrum using curve trades

Change tricrypto pool abi

---

src/entities/trades/gnosis-protocol/CoWTrade.ts
test/gnosis-protocol-trade.test.ts

Adds native support back to CoWTrade

bugfix: add native currency support to `CoWTrade`

---

src/entities/token.ts
src/entities/trades/routable-platform/RoutablePlatform.ts
src/entities/trades/uniswap-v2/constants.ts
src/entities/trades/utils.ts
src/errors.ts
src/utils.ts

This feature links tokens to the optimism chain.
I will also create a PR in the dapp and the "swapr-ecobridge-socket-lists" repo"

Add Optimism support

---

src/entities/trades/0x/constants.ts
src/entities/trades/0x/utils.ts
src/entities/trades/routable-platform/RoutablePlatform.ts

Added additional chains to 0xTrade including:
- Arbitrum
- Optmism
- Binance Smart Chain
Dapp pr https://github.com/ImpeccableHQ/swapr-dapp/pull/1704

0xTrade: Added support for arbitrum,bnb and optimism

---

src/entities/trades/0x/0xTrade.ts
src/entities/trades/0x/constants.ts
src/entities/trades/0x/utils.ts
src/entities/trades/OneInch/api.ts
src/entities/trades/constants/index.ts

0xTrade and 1inch refferer address

---

src/entities/trades/0x/0xTrade.ts
src/entities/trades/0x/types.ts
src/entities/trades/OneInch/OneInch.ts
src/entities/trades/interfaces/trade.ts
src/entities/trades/uniswap-v2/UniswapV2.ts
src/entities/trades/uniswap/Uniswap/Uniswap.ts

Implementing gas estimation on mainnet where possible
Currently:
1) 1Inch
2) 0xTrade
3) Uniswap
TO DO:
- UniswapV2 dexes
- Curve
- Cow

Gas estimation

---

src/entities/trades/gnosis-protocol/CoWTrade.ts

feat: update cowswap fee

---

.github/workflows/CI.yml
package-lock.json
src/constants/chains.ts
src/entities/trades/gnosis-protocol/CoWTrade.ts
src/entities/trades/swapr-v3/swapr-v3.spec.ts
src/entities/trades/uniswap/Uniswap/Uniswap.spec.ts
src/entities/trades/uniswap/Uniswap/Uniswap.ts
test/0x-trade.test.ts
test/curve-trade.test.ts
test/fees.test.ts

* Update CI runs-on OS version to a supported one by Github

[SWA-139][IMPROVEMENT] - Swapr SDK CI runners are not picking up jobs
